# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('productos', '0008_perdida'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('facturado', models.BooleanField()),
                ('efectivo', models.BooleanField()),
                ('observacion', models.CharField(max_length=100)),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Personas')),
                ('productos', models.ManyToManyField(through='ventas.detalle_venta', to='productos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Venta'),
        ),
    ]
