# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-07 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desbloqueo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flash', models.BooleanField(default=False)),
                ('imei', models.BooleanField(default=False)),
                ('liberacion', models.BooleanField(default=False)),
                ('cuenta', models.BooleanField(default=False)),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entregado', models.DateTimeField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pagado', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Modelo')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Personas')),
            ],
        ),
    ]
