# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField(default='http://www.lake-link.com/images/avatars/noAvatar.png')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaa', models.DateTimeField()),
                ('fechac', models.DateTimeField(blank=True, null=True)),
                ('montoa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('montoc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.CharField(max_length=100)),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Personas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comision2producto', to='productos.Producto')),
            ],
        ),
    ]
