# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='personas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comision2personas', to='personas.Personas'),
        ),
    ]
