# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_avatar_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fechac',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='montoc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
