# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_auto_20170821_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
