# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-04 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_caja_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comision',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
