# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('acreedor', models.CharField(max_length=70)),
                ('vencido', models.BooleanField(default=False)),
                ('pagado', models.BooleanField(default=False)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(default=1)),
                ('observacion', models.CharField(max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Perdida2producto', to='productos.Producto')),
            ],
        ),
    ]
