# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Perdida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('punto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cliente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stock_minimo', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=0)),
                ('barra', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, default='Nada', max_length=70, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Modelo')),
                ('precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Precio')),
            ],
        ),
        migrations.AddField(
            model_name='perdida',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
