# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='imagen',
            field=models.URLField(default='http://i.imgur.com/jtDKvFX.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sku',
            name='barra',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='genero',
            field=models.CharField(choices=[('varon', 'Varon'), ('mujer', 'Mujer'), ('unisex', 'Unisex'), ('nino', 'Nino'), ('nina', 'Nina')], max_length=15),
        ),
    ]
