# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_mercaderia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mercaderia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='mercaderia',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='mercaderia',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='barra',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Nada', max_length=70),
        ),
        migrations.DeleteModel(
            name='Mercaderia',
        ),
    ]
