# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20170810_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, default='Nada', max_length=70, null=True),
        ),
    ]
