# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20170810_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existencias',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='existencias',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Existencias',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
    ]
