# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('productos', '0008_perdida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('pagado', models.BooleanField(default=False)),
                ('devuelto', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Personas')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_consignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('consignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consignaciones.Consignacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='consignacion',
            name='productos',
            field=models.ManyToManyField(through='consignaciones.detalle_consignacion', to='productos.Producto'),
        ),
    ]
