from django.conf.urls import include, url
from .views import *

urlpatterns = [
    url(r'^categorias/agregar$', agregarcategoria, name='categoria_agregar'),
    url(r'^categorias/listar$', listarcategorias, name='categorias_listar'),
    url(r'^categorias/buscar-ajax$', buscarcategorias, name='categorias_buscar_ajax'),
    url(r'^categorias/editar/(?P<pk>[0-9]+)/$', editarcategorias, name='categorias_editar'),
    url(r'^categorias/eliminar/(?P<pk>[0-9]+)/$', eliminarcategorias, name='categorias_eliminar'),
    url(r'^marcas/agregar$', agregarmarca, name='marca_agregar'),
    url(r'^marcas/listar$', listarmarcas, name='marcas_listar'),
    url(r'^marcas/buscar-ajax$', buscarmarcas, name='marcas_buscar_ajax'),
    url(r'^marcas/editar/(?P<pk>[0-9]+)/$', editarmarcas, name='marcas_editar'),
    url(r'^marcas/eliminar/(?P<pk>[0-9]+)/$', eliminarmarcas, name='marcas_eliminar'),
    url(r'^modelos/agregar$', agregarmodelo, name='modelo_agregar'),
    url(r'^modelos/listar$', listarmodelos, name='modelos_listar'),
    url(r'^modelos/buscar-ajax$', buscarmodelos, name='modelos_buscar_ajax'),
    url(r'^modelos/editar/(?P<pk>[0-9]+)/$', editarmodelos, name='modelos_editar'),
    url(r'^modelos/eliminar/(?P<pk>[0-9]+)/$', eliminarmodelos, name='modelos_eliminar'),
    url(r'^precios/agregar$', agregarprecio, name='precio_agregar'),
    url(r'^precios/listar$', listarprecios, name='precios_listar'),
    url(r'^precios/buscar-ajax$', buscarprecios, name='precios_buscar_ajax'),
    url(r'^precios/editar/(?P<pk>[0-9]+)/$', editarprecios, name='precios_editar'),
    url(r'^precios/eliminar/(?P<pk>[0-9]+)/$', eliminarprecios, name='precios_eliminar'),
    url(r'^almacenes/agregar$', agregaralmacen, name='almacen_agregar'),
    url(r'^almacenes/listar$', listaralmacenes, name='almacenes_listar'),
    url(r'^almacenes/buscar-ajax$', buscaralmacenes, name='almacenes_buscar_ajax'),
    url(r'^almacenes/editar/(?P<pk>[0-9]+)/$', editaralmacenes, name='almacenes_editar'),
    url(r'^almacenes/eliminar/(?P<pk>[0-9]+)/$', eliminaralmacenes, name='almacenes_eliminar'),
    url(r'^productos/agregar$', agregarproducto, name='producto_agregar'),
    url(r'^productos/listar$', listarproductos, name='productos_listar'),
    url(r'^productos/buscar-ajax$', buscarproductos, name='productos_buscar_ajax'),
    url(r'^productos/buscar-ajax2$', buscarproductos2, name='productos_buscar_ajax2'),
    url(r'^productos/editar/(?P<pk>[0-9]+)/$', editarproductos, name='productos_editar'),
    url(r'^productos/eliminar/(?P<pk>[0-9]+)/$', eliminarproductos, name='productos_eliminar'),
    url(r'^sku/agregar$', agregarsku, name='sku_agregar'),
    url(r'^sku/listar$', listarsku, name='sku_listar'),
    url(r'^sku/buscar-ajax$', buscarsku, name='sku_buscar_ajax'),
    url(r'^sku/editar/(?P<pk>[0-9]+)/$', editarsku, name='sku_editar'),
    url(r'^sku/eliminar/(?P<pk>[0-9]+)/$', eliminarsku, name='sku_eliminar'),
    ]
