# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 20:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2017, 8, 11, 20, 7, 29, 513739, tzinfo=utc)),
        ),
    ]
