# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2017, 8, 10, 1, 14, 14, 332868, tzinfo=utc)),
        ),
    ]
