# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20170810_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2017, 8, 10, 16, 33, 54, 524656, tzinfo=utc)),
        ),
    ]
