# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20170810_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(verbose_name=datetime.datetime(2017, 8, 10, 21, 51, 50, 223657, tzinfo=utc)),
        ),
    ]
