# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_auto_20170810_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(),
        ),
    ]
