# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compra_estado'),
        ('compras', '0002_auto_20170811_1507'),
    ]

    operations = [
    ]
