# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-25 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_remove_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='unidades_vendidas',
            field=models.IntegerField(default=0),
        ),
    ]
