# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_auto_20170925_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_compra',
            old_name='unidades_vendidas',
            new_name='unidades_fuera',
        ),
        migrations.AlterField(
            model_name='detalle_compra',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
