# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=9)),
                ('sexo', models.BooleanField()),
                ('mayorista', models.BooleanField()),
                ('nacimiento', models.DateField()),
                ('datos', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
